codecov:
  notify:
    require_ci_to_pass: no
    wait_for_ci: no

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 70%
        threshold: 5%
    changes: on
    patch:
      default:
        target: 0%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment: false

ignore:
  - "platform/linux-generic/miniz/**/*"
