name: CI

on: [push]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install dependencies
      run: sudo apt install build-essential automake autoconf libtool pkg-config libssl-dev libpcap-dev libconfig-dev libcunit1-dev
    - uses: actions/checkout@v1
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
